apiVersion: v1
kind: Service
metadata:
  name: telemetry-postgres
spec:
  type: ClusterIP
  selector:
    app: telemetry-postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}


