apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-postgres
  template:
    metadata:
      labels:
        app: telemetry-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: telemetry-postgres-init


